# Generated by Django 5.0.6 on 2024-06-19 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('is_business_owner', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('longitude', models.FloatField(default=1)),
                ('latitude', models.FloatField(default=1)),
                ('food_category', models.CharField(choices=[('Israeli', 'Israeli'), ('Italian', 'Italian'), ('Chinese', 'Chinese'), ('Mexican', 'Mexican'), ('Grill', 'Grill'), ('Meat', 'Meat'), ('Seafood', 'Seafood'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Fast_food', 'Fast Food'), ('Dessert', 'Dessert'), ('Cafe', 'Cafe'), ('Bar', 'Bar'), ('Pub', 'Pub'), ('Brewery', 'Brewery'), ('Steakhouse', 'Steakhouse'), ('Sushi', 'Sushi'), ('Food_truck', 'Food Truck'), ('Bakery', 'Bakery'), ('Deli', 'Deli'), ('Juice_bar', 'Juice Bar'), ('Asian', 'Asian'), ('Vietnamese', 'Vietnamese'), ('Morrocan', 'Morrocan')], default='Israeli', max_length=100)),
                ('is_kosher', models.BooleanField(default=False)),
                ('has_vegan_option', models.BooleanField(default=False)),
                ('recommended_dishes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='place_images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(default='reutdimri24@gmail.com', on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
