# Generated by Django 5.0.6 on 2024-06-05 12:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Italian', 'Italian'), ('Chinese', 'Chinese'), ('Mexican', 'Mexican')], max_length=100)),
                ('is_cosher', models.BooleanField(default=False)),
                ('has_vegan_option', models.BooleanField(default=False)),
                ('recommended_dishes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodSupplier',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('supplier_email', models.EmailField(max_length=254, unique=True)),
                ('supplier_password', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=!]).{8,}$')])),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.place')),
            ],
        ),
    ]
