# Generated by Django 5.0.6 on 2024-05-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_journey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
