# Generated by Django 5.0.6 on 2024-06-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default='', upload_to='place_images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('Italian', 'Italian'), ('Chinese', 'Chinese'), ('Mexican', 'Mexican'), ('Gril', 'Gril'), ('Meat', 'Meat'), ('Seafood', 'Seafood'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Fast_food', 'Fast Food'), ('Dessert', 'Dessert'), ('Cafe', 'Cafe'), ('Bar', 'Bar'), ('Pub', 'Pub'), ('Brewery', 'Brewery'), ('Steakhouse', 'Steakhouse'), ('Sushi', 'Sushi'), ('Food_truck', 'Food Truck'), ('Bakery', 'Bakery'), ('Deli', 'Deli'), ('Juice_bar', 'Juice Bar'), ('Asian', 'Asian'), ('Vietnamese', 'Vietnamese')], max_length=100),
        ),
    ]
