# Generated by Django 5.0.6 on 2024-05-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_journey_journey_code_journey_id'),
        ('myapp', '0003_alter_journey_id'),
    ]

    operations = [
    ]
