# Generated by Django 5.0.6 on 2024-06-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_place_image_alter_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
