# Generated by Django 5.0.6 on 2024-05-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_merge_20240522_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='journey',
            name='duration',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='journey',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
