# Generated by Django 5.0.6 on 2024-06-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_place_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
