# Generated by Django 5.0.6 on 2024-06-06 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_place_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('Italian', 'Italian'), ('Chinese', 'Chinese'), ('Mexican', 'Mexican'), ('Gril', 'Gril'), ('Meat', 'Meat'), ('Seafood', 'Seafood'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Fast_food', 'Fast Food'), ('Dessert', 'Dessert'), ('Cafe', 'Cafe'), ('Bar', 'Bar'), ('Pub', 'Pub'), ('Brewery', 'Brewery'), ('Steakhouse', 'Steakhouse'), ('Sushi', 'Sushi'), ('Food_truck', 'Food Truck'), ('Bakery', 'Bakery'), ('Deli', 'Deli'), ('Juice_bar', 'Juice Bar'), ('Asian', 'Asian'), ('Vietnamese', 'Vietnamese'), ('Morrocan', 'Morrocan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='rate',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
