# Generated by Django 5.0.6 on 2024-05-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_users_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
